---
title: "hw2"
author: "spalalidelen2"
date: "4/1/2020"
output: html_document
---


## Normalize the path:

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('../../')) 
```



### Flint-Garcia et al., 2009 data

```{r}
f <- read.delim("data/journal.pone.0007433.s001.txt", header=TRUE)
# Convert missing data to NA
f[f=="."] <- NA

# four environments
table(f$Env)

f$INBRED <- as.factor(f$INBRED)
f$Env <- as.factor(f$Env)
```

$$
H^2 = \frac{V_G}{V_P}
$$
$$
H^2 = \frac{V_G}{V_G + V_E}
$$
$$
V_G = \frac{MS(G)- MS(error)}{n}
$$ 




## CobWt_Inbred
```{r}
# four environments
table(f$Env)

f$INBRED <- as.factor(f$INBRED)
f$Env <- as.factor(f$Env)
# tricky part, be careful:
f$CobWt_Inbred  <- as.numeric(as.character((f$CobWt_Inbred)))

fit <- lm(CobWt_Inbred ~ INBRED + Env, data=f)
anova(fit)
```



```{r}
Vg =  (48.15 - 14.05)/4
Ve = 0
Vge = 14.05

H2_CobWt_Inbred = Vg/(Vg + Ve + Vge)
H2_CobWt_Inbred
```

## CobWt_Hyb
```{r}
# four environments
table(f$Env)

f$INBRED <- as.factor(f$INBRED)
f$Env <- as.factor(f$Env)
# tricky part, be careful:
f$CobWt_Hyb  <- as.numeric(as.character((f$CobWt_Hyb)))

fit <- lm(CobWt_Hyb ~ INBRED + Env, data=f)
anova(fit)
```


```{r}
Vg =  (78.19 - 19.55)/4
Ve = 0
Vge = 19.55

H2_CobWt_Hyb = Vg/(Vg + Ve + Vge)
H2_CobWt_Hyb
```




## EarLength_Inbred 
```{r}
# four environments
table(f$Env)

f$INBRED <- as.factor(f$INBRED)
f$Env <- as.factor(f$Env)
# tricky part, be careful:
f$EarLength_Inbred  <- as.numeric(as.character((f$EarLength_Inbred)))

fit <- lm(EarLength_Inbred ~ INBRED + Env, data=f)
anova(fit)
```


```{r}
Vg =  (846 - 233)/4
Ve = 0
Vge = 233

H2_EarLength_Inbred = Vg/(Vg + Ve + Vge)
H2_EarLength_Inbred
```


## EarLength_Hyb 
```{r}
# four environments
table(f$Env)

f$INBRED <- as.factor(f$INBRED)
f$Env <- as.factor(f$Env)
# tricky part, be careful:
f$EarLength_Hyb  <- as.numeric(as.character((f$EarLength_Hyb)))

fit <- lm(EarLength_Hyb ~ INBRED + Env, data=f)
anova(fit)
```


```{r}
Vg =  (776 - 164)/4
Ve = 0
Vge = 164

H2_EarLength_Hyb = Vg/(Vg + Ve + Vge)
H2_EarLength_Hyb
```




## PLTHT_Inbred
```{r}
# four environments
table(f$Env)

f$INBRED <- as.factor(f$INBRED)
f$Env <- as.factor(f$Env)
# tricky part, be careful:
f$PLTHT_Inbred  <- as.numeric(as.character((f$PLTHT_Inbred)))

fit <- lm(PLTHT_Inbred ~ INBRED + Env, data=f)
anova(fit)
```


```{r}
Vg =  (1781 - 192)/4
Ve = 0
Vge = 192

H2_PLTHT_Inbred = Vg/(Vg + Ve + Vge)
H2_PLTHT_Inbred
```


## PLTHT_Hyb
```{r}
# four environments
table(f$Env)

f$INBRED <- as.factor(f$INBRED)
f$Env <- as.factor(f$Env)
# tricky part, be careful:
f$PLTHT_Hyb  <- as.numeric(as.character((f$PLTHT_Hyb)))

fit <- lm(PLTHT_Hyb ~ INBRED + Env, data=f)
anova(fit)
```



```{r}
Vg =  (2414 - 168)/4
Ve = 0
Vge = 168

H2_PLTHT_Hyb = Vg/(Vg + Ve + Vge)
H2_PLTHT_Hyb
```




```{r}
H2_all_traits <- c("H2_CobWt_Inbred", "H2_CobWt_Hyb", "H2_EarLength_Inbred", "H2_EarLength_Hyb", "H2_PLTHT_Inbred", "H2_PLTHT_Hyb")

H2_all_values <- c(0.3776301, 0.4285297, 0.3967638, 0.4826498, 0.6741621, 0.7697053)
```


```{r}
library(ggplot2)
barplot(H2_all_values, main = "the comparision of heritability in inbreds and hybrids", col = c("dark red", "maroon", "dark red", "maroon", "dark red", "maroon"), ylab = "heritability", names.arg = c("CobWt_Inbred", "CobWt_Hyb", "EarLength_Inbred", "EarLength_Hyb", "PLTHT_Inbred", "PLTHT_Hyb"))
```
