---
title: "hw2"
author: "spalalidelen2"
date: "4/1/2020"
output: html_document
---


## Normalize the path:

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
#knitr::opts_knit$set(root.dir=normalizePath('../../')) 
```



### Flint-Garcia et al., 2009 data

```{r}
f <- read.delim("../data/journal.pone.0007433.s001.txt", header=TRUE)
# Convert missing data to NA
f[f=="."] <- NA

# four environments
table(f$Env)

f$INBRED <- as.factor(f$INBRED)
f$Env <- as.factor(f$Env)
# tricky part, be careful:
f$TotKnlWt_Inbred  <- as.numeric(as.character((f$TotKnlWt_Inbred)))

fit <- lm(TotKnlWt_Inbred ~ INBRED + Env, data=f)
anova(fit)
```

$$
H^2 = \frac{V_G}{V_G + V_E}
$$
With $(V_G =  MS(G) - MS(error)/n$ 

```{r}
Vg =  (603.8 - 307.5)/4
Ve = 307.5

H2 = Vg/(Vg + Ve)
H2
```

### Cob Dia
```{r}
f <- read.delim("../data/journal.pone.0007433.s001.txt", header=TRUE)
# Convert missing data to NA
f[f=="."] <- NA

# four environments
table(f$Env)

f$INBRED <- as.factor(f$INBRED)
f$Env <- as.factor(f$Env)
# tricky part, be careful:
f$CobDia_Inbred  <- as.numeric(as.character((f$CobDia_Inbred)))

fit <- lm(CobDia_Inbred ~ INBRED + Env + INBRED*Env, data=f)
anova(fit)
```



## CobWt_Inbred
```{r}
f <- read.delim("../data/journal.pone.0007433.s001.txt", header=TRUE)
# Convert missing data to NA
f[f=="."] <- NA

# four environments
table(f$Env)

f$INBRED <- as.factor(f$INBRED)
f$Env <- as.factor(f$Env)
# tricky part, be careful:
f$CobWt_Inbred  <- as.numeric(as.character((f$CobWt_Inbred)))

fit <- lm(CobWt_Inbred ~ INBRED + Env, data=f)
anova(fit)
```



```{r}
Vg =  (22.108 - 4.063)/4
Ve = 0
Vge = 4.063

H2 = Vg/(Vg + Ve + Vge)
H2
```

## CobWt_Hyb
```{r}
f <- read.delim("../data/journal.pone.0007433.s001.txt", header=TRUE)
# Convert missing data to NA
f[f=="."] <- NA

# four environments
table(f$Env)

f$INBRED <- as.factor(f$INBRED)
f$Env <- as.factor(f$Env)
# tricky part, be careful:
f$CobWt_Hyb  <- as.numeric(as.character((f$CobWt_Hyb)))

fit <- lm(CobWt_Hyb ~ INBRED + Env, data=f)
anova(fit)
```


## EarLength_Inbred 
```{r}
f <- read.delim("../data/journal.pone.0007433.s001.txt", header=TRUE)
# Convert missing data to NA
f[f=="."] <- NA

# four environments
table(f$Env)

f$INBRED <- as.factor(f$INBRED)
f$Env <- as.factor(f$Env)
# tricky part, be careful:
f$EarLength_Inbred  <- as.numeric(as.character((f$EarLength_Inbred)))

fit <- lm(EarLength_Inbred ~ INBRED + Env, data=f)
anova(fit)
```





## EarLength_Hyb 
```{r}
f <- read.delim("../data/journal.pone.0007433.s001.txt", header=TRUE)
# Convert missing data to NA
f[f=="."] <- NA

# four environments
table(f$Env)

f$INBRED <- as.factor(f$INBRED)
f$Env <- as.factor(f$Env)
# tricky part, be careful:
f$EarLength_Hyb  <- as.numeric(as.character((f$EarLength_Hyb)))

fit <- lm(EarLength_Hyb ~ INBRED + Env, data=f)
anova(fit)
```






## PLTHT_Inbred
```{r}
f <- read.delim("../data/journal.pone.0007433.s001.txt", header=TRUE)
# Convert missing data to NA
f[f=="."] <- NA

# four environments
table(f$Env)

f$INBRED <- as.factor(f$INBRED)
f$Env <- as.factor(f$Env)
# tricky part, be careful:
f$PLTHT_Inbred  <- as.numeric(as.character((f$PLTHT_Inbred)))

fit <- lm(PLTHT_Inbred ~ INBRED + Env, data=f)
anova(fit)
```





## PLTHT_Hyb
```{r}
f <- read.delim("../data/journal.pone.0007433.s001.txt", header=TRUE)
# Convert missing data to NA
f[f=="."] <- NA

# four environments
table(f$Env)

f$INBRED <- as.factor(f$INBRED)
f$Env <- as.factor(f$Env)
# tricky part, be careful:
f$PLTHT_Hyb  <- as.numeric(as.character((f$PLTHT_Hyb)))

fit <- lm(PLTHT_Hyb ~ INBRED + Env, data=f)
anova(fit)
```